// ecos — Israeli space ecosystem data seed

const SECTORS = [
  { id: "earth-obs",     label: "תצפית מהלוויין",    color: "oklch(0.72 0.20 250)" },
  { id: "comms",         label: "תקשורת לוויינית",   color: "oklch(0.72 0.20 295)" },
  { id: "ai-data",       label: "AI ועיבוד נתונים",  color: "oklch(0.72 0.20 330)" },
  { id: "propulsion",    label: "הנעה ושינוע",       color: "oklch(0.72 0.22 80)"  },
  { id: "manufacturing", label: "ייצור ומבנים",      color: "oklch(0.72 0.18 145)" },
  { id: "life-sci",      label: "מדעי החיים",        color: "oklch(0.72 0.20 185)" },
  { id: "energy",        label: "אנרגיה בחלל",      color: "oklch(0.78 0.18 55)"  },
  { id: "launchers",     label: "שיגור",             color: "oklch(0.65 0.22 200)" },
  { id: "sar",           label: "SAR / מכ\"מ",       color: "oklch(0.68 0.18 30)"  },
];

const STAGES = ["Seed", "Series A", "Series B", "Series C", "Growth", "Public"];

const COMPANIES = [
  {
    id: "strasa-technologies",
    name: "Strasa Technologies",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ראש העין",
    stage: "Seed",
    size: "1-10",
    founded: 2022,
    fundingM: 0,
    score: 57,
    strategic: false,
    readiness: "",
    sectors: ["defense", "earth-obs"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "High-altitude Pseudo-satellite for High-resolution Aerial Imagery",
  },
  {
    id: "israel-aerospace-industries",
    name: "Israel Aerospace Industries",
    country: "Israel",
    flag: "🇮🇱",
    hq: "עיר התעופה",
    stage: "Public",
    size: "1000+",
    founded: 1953,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Military and Commercial Aerospace Technology",
  },
  {
    id: "moonscape",
    name: "Moonscape",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ישראל",
    stage: "Seed",
    size: "1-10",
    founded: 2020,
    fundingM: 0,
    score: 58,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Lunar Services",
  },
  {
    id: "tti-ray-q",
    name: "TTI Ray-Q",
    country: "Israel",
    flag: "🇮🇱",
    hq: "לוד",
    stage: "Series A",
    size: "11-50",
    founded: 1969,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Electrical Products for Military and Aerospace Markets",
  },
  {
    id: "ramon-space",
    name: "Ramon.Space",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יוקנעם",
    stage: "Series B",
    size: "51-200",
    founded: 2004,
    fundingM: 0,
    score: 86,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing", "launchers"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Space-resilient Super-computer Systems",
  },
  {
    id: "ashot-ashkelon",
    name: "Ashot Ashkelon",
    country: "Israel",
    flag: "🇮🇱",
    hq: "אשקלון",
    stage: "Series B",
    size: "51-200",
    founded: 1970,
    fundingM: 0,
    score: 90,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Transmission Gearboxes for Aerospace and Defense",
  },
  {
    id: "noohra",
    name: "Noohra",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ירקונה",
    stage: "Seed",
    size: "1-10",
    founded: 2023,
    fundingM: 0,
    score: 56,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "GHG Emission Monitoring with SWIR Hyperspectral Imaging",
  },
  {
    id: "spacecom-communications",
    name: "Spacecom Communications",
    country: "Israel",
    flag: "🇮🇱",
    hq: "רמת גן",
    stage: "Series B",
    size: "51-200",
    founded: 1989,
    fundingM: 0,
    score: 86,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Fixed-satellite Communication Services",
  },
  {
    id: "tehiru",
    name: "Tehiru",
    country: "Israel",
    flag: "🇮🇱",
    hq: "שדה חמד",
    stage: "Seed",
    size: "1-10",
    founded: 2020,
    fundingM: 0,
    score: 66,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Air-launched Hybrid Rocket Booster",
  },
  {
    id: "sky-and-space-global",
    name: "Sky and Space Global",
    country: "Israel",
    flag: "🇮🇱",
    hq: "שוהם",
    stage: "Seed",
    size: "1-10",
    founded: 2015,
    fundingM: 0,
    score: 71,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Nanosatellite Communication Network",
  },
  {
    id: "spaceil",
    name: "SpaceIL",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Series B",
    size: "51-200",
    founded: 2010,
    fundingM: 0,
    score: 83,
    strategic: false,
    readiness: "",
    sectors: ["defense", "launchers"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Lunar Landing Spacecraft",
  },
  {
    id: "foxcom",
    name: "Foxcom",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ארה\"ב",
    stage: "Series A",
    size: "11-50",
    founded: 1993,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms", "sar"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "RF-over-fiber Solutions",
  },
  {
    id: "bareket-astro",
    name: "Bareket Astro",
    country: "Israel",
    flag: "🇮🇱",
    hq: "מודיעין",
    stage: "Seed",
    size: "1-10",
    founded: 2018,
    fundingM: 0,
    score: 59,
    strategic: false,
    readiness: "",
    sectors: ["defense", "launchers"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Digital Planetarium Systems and Precision Optics for Space Observatories",
  },
  {
    id: "agrimapic",
    name: "Agrimapic",
    country: "Israel",
    flag: "🇮🇱",
    hq: "חולון",
    stage: "Seed",
    size: "1-10",
    founded: 2015,
    fundingM: 0,
    score: 68,
    strategic: false,
    readiness: "",
    sectors: ["defense", "earth-obs", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Agrimapic has been developing Drone-Enabled Systems, providing advanced Photo Geometric Services complete with professional analysis systems in order to provide customers unique and powerful big data information. This data can then be delivered as 2D or 3D images as well as models.",
  },
  {
    id: "acs",
    name: "ACS",
    country: "Israel",
    flag: "🇮🇱",
    hq: "קיבוץ עין חרוד",
    stage: "Seed",
    size: "1-10",
    founded: 2003,
    fundingM: 0,
    score: 77,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Aero-Magnesium supplies a wide range of technological solutions and high-end magnesium parts and sub-assemblies of civil applications to the aerospace, space and electro-optics industries worldwide.",
  },
  {
    id: "air-one",
    name: "Air One",
    country: "Israel",
    flag: "🇮🇱",
    hq: "פרדס חנה-כרכור",
    stage: "Series A",
    size: "11-50",
    founded: 2017,
    fundingM: 0,
    score: 79,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data", "propulsion", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "AIR is a leading dual-use aerospace OEM developing advanced eVTOL aircraft for both uncrewed cargo logistics, Defense, and FAA-certified piloted flight.",
  },
  {
    id: "creation-space",
    name: "Creation Space",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "11-50",
    founded: 2023,
    fundingM: 0,
    score: 69,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Creation Space is engaged in supporting technological developments in the field of deep space.",
  },
  {
    id: "kikfin",
    name: "KikFin",
    country: "Israel",
    flag: "🇮🇱",
    hq: "חיפה",
    stage: "Seed",
    size: "1-10",
    founded: 2019,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense", "propulsion", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "KikFin is the first underwater Jetpack, designed to elevate surfing and diving experience around the world. KikFin thruster easily connects to every surfboard/SUP and it allows optimal hydrodynamics to cause minimal drag. It allows the surfer/Sup to have extra power and stay safe against strong currents at sea.",
  },
  {
    id: "desert-space-corporation",
    name: "Desert Space Corporation",
    country: "Israel",
    flag: "🇮🇱",
    hq: "שדה ניצן",
    stage: "Seed",
    size: "1-10",
    founded: 2022,
    fundingM: 0,
    score: 65,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Desert Space Corporation is a commercial space company, which works with Israeli aerospace engineers, scientists and talents in the fields of space research and space technology.",
  },
  {
    id: "arazim",
    name: "Arazim",
    country: "Israel",
    flag: "🇮🇱",
    hq: "לוד",
    stage: "Seed",
    size: "1-10",
    founded: 1989,
    fundingM: 0,
    score: 77,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Arazim is developer of embedded high-performance, miniature,  low-power systems, using the latest available technology, sensors and ICs.",
  },
  {
    id: "flyvercity",
    name: "Flyvercity",
    country: "Israel",
    flag: "🇮🇱",
    hq: "נתניה",
    stage: "Seed",
    size: "1-10",
    founded: 2022,
    fundingM: 0,
    score: 65,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Flyvercity is leveraging new capabilities of the 5G network by creating ground-based tactical deconfliction solution for demanding city environment. The company's core multi-access edge computing application provides remote pilots with tactical collision avoidance advisories via 5G network slice.",
  },
  {
    id: "flytrex",
    name: "Flytrex",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Series A",
    size: "11-50",
    founded: 2013,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense", "earth-obs"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Flytrex is Flytrex is a provider of a drone delivery service, intended to provide fast and contact-free deliveries from local restaurants and grocery stores to suburban areas.",
  },
  {
    id: "exom",
    name: "EXOM",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "1-10",
    founded: 2021,
    fundingM: 0,
    score: 66,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "EXOM integrates sustainable building elements alongside IoT architecture, Biophilic designs, VR and discourse analysis technologies in order to create sustainable, efficient and protective habitat solutions on Earth, Moon and Mars.",
  },
  {
    id: "eyeviation",
    name: "Eyeviation",
    country: "Israel",
    flag: "🇮🇱",
    hq: "פתח תקווה",
    stage: "Seed",
    size: "1-10",
    founded: 2019,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Eyeviation specializes in the development and integration of advanced eye-tracking technology applications for aviation. By measuring and analyzing aircrew performance, Eyeviation can improve and maximize their abilities in order to achieve an efficient, effective and safe flight.",
  },
  {
    id: "attis-aviation",
    name: "Attis Aviation",
    country: "Israel",
    flag: "🇮🇱",
    hq: "קיסריה",
    stage: "Seed",
    size: "11-50",
    founded: 2021,
    fundingM: 0,
    score: 70,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Attis specializes in developing solutions in the field of UAVs with an emphasis on vertical takeoff and landing (VTOL) systems. The company's system uses a fixed wing combined with a rotary mechanism, which allows it to operate with high efficiency in open terrain and in diverse tactical conditions.",
  },
  {
    id: "identa",
    name: "IDenta",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ירושלים",
    stage: "Seed",
    size: "1-10",
    founded: 1997,
    fundingM: 0,
    score: 76,
    strategic: false,
    readiness: "",
    sectors: ["defense", "life-sci"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "IDenta has been recognized as a worldwide leader in the development of proprietary on-site Drug, Precursor of Drugs and Explosive Detection Kits.",
  },
  {
    id: "moonshot-technologies",
    name: "Moonshot Technologies",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ריש'פון",
    stage: "Seed",
    size: "1-10",
    founded: 2021,
    fundingM: 0,
    score: 66,
    strategic: false,
    readiness: "",
    sectors: ["defense", "launchers"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Moonshot develops technology that offers light, highly affordable and on-demand commercial access to space.",
  },
  {
    id: "moonshot-space",
    name: "Moonshot Space",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Series A",
    size: "11-50",
    founded: 2024,
    fundingM: 0,
    score: 74,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Moonshot developing a new method for launching cargo into space without the need for a launcher (rocket). The idea is to greatly reduce the costs of launching into space, which are based on expensive and large launcher rockets, of which the payload itself is a few percent of the total mass of the rocket.",
  },
  {
    id: "lowental",
    name: "Lowental",
    country: "Israel",
    flag: "🇮🇱",
    hq: "מישר",
    stage: "Seed",
    size: "11-50",
    founded: 2018,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense", "propulsion", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Lowental is a developer of a hybrid propulsion system, designed to provide an in-house closed-loop design, integration and test bench experiments, all perfectly adapted to UAV needs and requirements.",
  },
  {
    id: "lulav-space",
    name: "Lulav Space",
    country: "Israel",
    flag: "🇮🇱",
    hq: "חיפה",
    stage: "Seed",
    size: "1-10",
    founded: 2021,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Lulav developer of a space robotics navigation system, designed to support spacecraft landings.",
  },
  {
    id: "odysight-ai",
    name: "Odysight.AI",
    country: "Israel",
    flag: "🇮🇱",
    hq: "עומר",
    stage: "Series A",
    size: "11-50",
    founded: 2019,
    fundingM: 0,
    score: 79,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Odysight.ai is pioneering the Predictive Maintenance (PdM) and Condition Based Monitoring (CBM) markets with its visualization and AI platform. Providing video sensor-based solutions for critical systems in the aviation, transportation, and energy industries, Odysight.",
  },
  {
    id: "microkim",
    name: "Microkim",
    country: "Israel",
    flag: "🇮🇱",
    hq: "מגדל העמק",
    stage: "Series A",
    size: "11-50",
    founded: 1972,
    fundingM: 0,
    score: 82,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Microkim Develops manufactures & markets products that are being implemented in Military Radar Systems, Elint & Commint and in Wireless communications systems.",
  },
  {
    id: "mobideo-israel",
    name: "Mobideo Israel",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ראש העין",
    stage: "Series A",
    size: "11-50",
    founded: 2000,
    fundingM: 0,
    score: 85,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing", "life-sci"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Mobideo is a global hi-tech company transforming the way industrial workforces operate and perform.",
  },
  {
    id: "gorilla-link",
    name: "Gorilla Link",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "1-10",
    founded: 2019,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms", "sar"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "GorillaLink is a Satellite IoT connectivity company offering a Platform‑as‑a‑Service that virtualizes satellite networks to deliver always‑on device connectivity “any industry, anytime, anywhere.",
  },
  {
    id: "sital",
    name: "Sital",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כפר סבא",
    stage: "Series A",
    size: "11-50",
    founded: 1993,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Sital Technology develops products and expertise for communication bus applications in the avionics, aerospace and automotive industries.",
  },
  {
    id: "novalert",
    name: "NOVAlert",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הוד השרון",
    stage: "Seed",
    size: "1-10",
    founded: 2020,
    fundingM: 0,
    score: 66,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "NOVAlert IVS Ltd. develops smart non-contact biometric solutions for driver monitoring (DMS), smart cockpit pilot monitoring, and high occupancy vehicles (HOV) passenger counting in carpools.",
  },
  {
    id: "tupaia",
    name: "Tupaia",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "1-10",
    founded: 2020,
    fundingM: 0,
    score: 69,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Tupaia specializes in high precision positioning solutions within the cloud computing industry. The company offers a cloud-based positioning service that integrates with GNSS receivers and provides accurate location data for various applications.",
  },
  {
    id: "cielo",
    name: "Cielo",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ירושלים",
    stage: "Series A",
    size: "11-50",
    founded: 2014,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Cielo is a global technology expert of inertial solutions, including reference, control, stabilization and navigation solutions for defense and commercial applications on land, air, marine and space.",
  },
  {
    id: "skylock-4g",
    name: "Skylock 4G",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יבנה",
    stage: "Series B",
    size: "51-200",
    founded: 1998,
    fundingM: 0,
    score: 88,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Skylock is a provider of vehicle tracking, anti-theft, and fleet security systems operating under a licensed security framework. It integrates GPS-based monitoring, remote control, and operational response services through a centralized command center and field teams.",
  },
  {
    id: "imco-industries",
    name: "IMCO Industries",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל חנן",
    stage: "Series C",
    size: "201-500",
    founded: 1974,
    fundingM: 0,
    score: 94,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "IMCO Industries is a leading Israeli defense company that specializes in the development, design and production of mechanical, electro-mechanical, electrical and electronic products, assemblies and sub-assemblies for airborne, land and naval applications.",
  },
  {
    id: "genesis-ew",
    name: "Genesis EW",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יהוד-מונוסון",
    stage: "Series A",
    size: "11-50",
    founded: 2004,
    fundingM: 0,
    score: 82,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Genesis offers a large scale of tactical intelligence solutions with advanced operational capabilities integrating to land, sea and air EW systems for symmetric as well as asymmetric warfare.",
  },
  {
    id: "armonic",
    name: "Armonic",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "1-10",
    founded: 2008,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Armonic is a software development company specializing in spatial computing and augmented/mixed reality (AR/MR) platforms. Its solutions provide hardware‑agnostic software that allows enterprises to design, deploy, and manage spatial AR/MR applications.",
  },
  {
    id: "simigon",
    name: "SimiGon",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הרצליה",
    stage: "Series A",
    size: "11-50",
    founded: 1998,
    fundingM: 0,
    score: 85,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "SimiGon is a leading developer and supplier of distributed simulation solutions for defence and civilian applications. SimiGon is the creator of SIMbox, a leading PC-based platform for creating, managing and deploying simulation-based content across multiple domains.",
  },
  {
    id: "go4a",
    name: "Go4A",
    country: "Israel",
    flag: "🇮🇱",
    hq: "קיבוץ גזית",
    stage: "Seed",
    size: "1-10",
    founded: 2021,
    fundingM: 0,
    score: 66,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Go4A make a unique drone platform that can get inside a dense urban area, roam inside buildings and bunkers and perform various tasks with a higher level of real-time, FPV telepresence and control, keeping the operator away.",
  },
  {
    id: "hartech",
    name: "HarTech",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הרצליה",
    stage: "Series A",
    size: "11-50",
    founded: 2005,
    fundingM: 0,
    score: 85,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "HarTech Technologies is an innovative and dynamic company specialized in development, integration and setting to work of advanced command and control systems, simulation infrastructure solutions, and advance tactical training solutions.",
  },
  {
    id: "airspace-ix",
    name: "Airspace IX",
    country: "Israel",
    flag: "🇮🇱",
    hq: "",
    stage: "Seed",
    size: "1-10",
    founded: 2017,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "AirspaceIX develops the next generation broadband wireless technology platforms and user terminals. The company provide a low cost systems to bring the reach of the global internet to rural communities and underserved suburban areas with the highest possible broadband connectivity services.",
  },
  {
    id: "senseer",
    name: "Senseer",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הרצליה",
    stage: "Seed",
    size: "11-50",
    founded: 2009,
    fundingM: 0,
    score: 75,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Secubit develops and manufactures innovative products to military and law enforcement agencies. Secubit has developed the WL™ - a new revolutionary system that enables the real-time recording and storing of gunfire data.",
  },
  {
    id: "istar",
    name: "iSTAR",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כפר סבא",
    stage: "Seed",
    size: "11-50",
    founded: 2016,
    fundingM: 0,
    score: 74,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "iSTAR manufactures innovative, advanced surveillance and intelligence systems for both the military and HLS markets. iSTAR specializes in the development, manufacturing and marketing of Unmanned Aerial Vehicles (UAV), such as fixed-wing & multi-rotor UAVs.",
  },
  {
    id: "sos",
    name: "SOS",
    country: "Israel",
    flag: "🇮🇱",
    hq: "נתניה",
    stage: "Seed",
    size: "1-10",
    founded: 1971,
    fundingM: 0,
    score: 71,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Source of Sound (SOS) is a world leader in tactical communication and hearing protection. In recent years, SOS has developed extremely efficient in-ear hearing protection systems which enhance the users’ communications (radio/ intercom) capabilities.",
  },
  {
    id: "lit",
    name: "LIT",
    country: "Israel",
    flag: "🇮🇱",
    hq: "לוד",
    stage: "Series A",
    size: "11-50",
    founded: 1996,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Latent Image has developed a technology that allows images – invisible to the naked eye – to be embedded in labels, tags, stickers and id cards. The images can be used to easily authenticate original products, documents and id cards.",
  },
  {
    id: "wespace",
    name: "WeSpace",
    country: "Israel",
    flag: "🇮🇱",
    hq: "רעננה",
    stage: "Seed",
    size: "1-10",
    founded: 2019,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense", "launchers"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "WeSpace Technologies was established to develop an autonomously flying robotic systems for lunar and deep-space exploration. WeSpace's flagship project is an autonomous hopper for exploring the Moon.",
  },
  {
    id: "mctech",
    name: "MCTECH",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כפר סבא",
    stage: "Seed",
    size: "11-50",
    founded: 2014,
    fundingM: 0,
    score: 75,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing", "sar"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "MCTECH is a leading international RF Technology system manufacturer, specializes in the design, development and manufacturing of high-end RF jammers.",
  },
  {
    id: "beeper",
    name: "Beeper",
    country: "Israel",
    flag: "🇮🇱",
    hq: "רמת גן",
    stage: "Growth",
    size: "201-500",
    founded: 1988,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Beeper Communications Israel was established by Motorola and local partners. Since then, has served as the premier provider of emergency communication and critical messaging services for the leading security, military and homeland defense organizations.",
  },
  {
    id: "unibeam",
    name: "Unibeam",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הוד השרון",
    stage: "Seed",
    size: "1-10",
    founded: 2016,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Unibeam's platform packages SIM-based authentication (physical or eSIM) with its proprietary technology & focus on customer experience to create the most secure fraud-prevention solution in a 0-touch & trust environment.",
  },
  {
    id: "urban-aeronautics",
    name: "Urban Aeronautics",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יבנה",
    stage: "Seed",
    size: "11-50",
    founded: 2001,
    fundingM: 0,
    score: 77,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Urban Aeronautics has developed advanced aerodynamic technologies that are the basis for an entirely new family of internal rotor (ducted fan) aircraft known as Fancraft™. UrbanAero capitalizes on its extensive portfolio of Intellectual Property via two subsidiary companies, Tactical Robotics Ltd.",
  },
  {
    id: "vectria",
    name: "Vectria",
    country: "Israel",
    flag: "🇮🇱",
    hq: "אשקלון",
    stage: "Series A",
    size: "11-50",
    founded: 2002,
    fundingM: 0,
    score: 82,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Vectria Technologies specializes in RF to mmWaves design and manufacturing, delivering state of the art added value products and solutions. Vectria was founded in 2002 to deliver innovative Microwave solutions along with cost effective high repeatability implementations.",
  },
  {
    id: "bluebird-aero-systems",
    name: "BlueBird Aero Systems",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כדימה-זורן",
    stage: "Series B",
    size: "51-200",
    founded: 2002,
    fundingM: 0,
    score: 90,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Bluebird specializes in the design, development and production of tactical UAS and peripheral equipment and delivers combat proven solutions.",
  },
  {
    id: "batm",
    name: "BATM",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הוד השרון",
    stage: "Public",
    size: "1000+",
    founded: 1992,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "BATM is a leading provider of real-time technologies with two divisions providing networking and cyber solutions and biomedical systems.  These two divisions have been built on the creation of strong intellectual property backed by strong patents.",
  },
  {
    id: "aeromaoz",
    name: "AeroMaoz",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יבנה",
    stage: "Series B",
    size: "51-200",
    founded: 1980,
    fundingM: 0,
    score: 89,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "AEROMAOZ is a world renowned designer and manufacturer of control panels, multi function displays, grips, lights and night-vision cockpit conversions.",
  },
  {
    id: "lingacom",
    name: "Lingacom",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "1-10",
    founded: 2012,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Lingacom’s state-of-the-art muon detection system provides muon-based detection solutions for the homeland security, civil engineering, archaeological, industrial, and mining exploration industries.",
  },
  {
    id: "wizlan",
    name: "WizLAN",
    country: "Israel",
    flag: "🇮🇱",
    hq: "חיפה",
    stage: "Seed",
    size: "1-10",
    founded: 1996,
    fundingM: 0,
    score: 71,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "WizLAN is an internationally recognized designer and manufacturer of a wide choice of fiber optic connectivity, distribution and access solutions for FTTD, FTTO, Control & Security, Industrial & Outdoor, Cyber Network Security and the global LAN markets.",
  },
  {
    id: "newrocket",
    name: "NewRocket",
    country: "Israel",
    flag: "🇮🇱",
    hq: "נתניה",
    stage: "Seed",
    size: "1-10",
    founded: 2014,
    fundingM: 0,
    score: 69,
    strategic: false,
    readiness: "",
    sectors: ["defense", "propulsion", "manufacturing", "energy"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "NewRocket: Gel Propellant Technology for Space and Aviation. NewRocket is developing advanced, environmentally friendly (\\\"Green Propulsion\\\") rocket engines based on innovative gel-propellant technology.",
  },
  {
    id: "vorpal",
    name: "Vorpal",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כפר סבא",
    stage: "Seed",
    size: "1-10",
    founded: 2009,
    fundingM: 0,
    score: 70,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Vorpal focusing on cutting-edge signal analysis products and solutions. VigilAir, Vorpal’s drone situational awareness solution, provides ultra-sensitive detection coupled with highly accurate geolocation and tracking for drone aerial situational awareness with unique clarity.",
  },
  {
    id: "aerosol",
    name: "AeroSol",
    country: "Israel",
    flag: "🇮🇱",
    hq: "פתח תקווה",
    stage: "Series A",
    size: "11-50",
    founded: 2007,
    fundingM: 0,
    score: 80,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "AeroSol, after more than a decade in aerospace manufacturing, has become a market leader in the field of the composite materials. With a team of engineering experts, Aero Sol takes pride in its ability to accompany a client from designing phases throughout manufacturing and mass production as a one-stop-shop.",
  },
  {
    id: "omnisys",
    name: "Omnisys",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ראש העין",
    stage: "Series B",
    size: "51-200",
    founded: 2000,
    fundingM: 0,
    score: 91,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Omnisys provides combat-proven decision support systems designed to maximize the success of operational missions. The company's solutions provide decision makers with real-time recommendations and insights to enable optimal planning, asset utilization, and response.",
  },
  {
    id: "commcrete",
    name: "Commcrete",
    country: "Israel",
    flag: "🇮🇱",
    hq: "שוהם",
    stage: "Series A",
    size: "11-50",
    founded: 2021,
    fundingM: 0,
    score: 76,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Commcrete is a developer of communication technology, intended to provide narrow-band satellite connectivity for both voice and data.",
  },
  {
    id: "wonder-robotics",
    name: "WONDER ROBOTICS",
    country: "Israel",
    flag: "🇮🇱",
    hq: "נתניה",
    stage: "Seed",
    size: "11-50",
    founded: 2020,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Autonomous  Solution for Drones",
  },
  {
    id: "rt",
    name: "RT",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יבנה",
    stage: "Series A",
    size: "11-50",
    founded: 1996,
    fundingM: 0,
    score: 84,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "RT is a designer, developer and manufacturer of the Skystar family of aerostats for use in intelligence, surveillance, reconnaissance and communications applications.",
  },
  {
    id: "paxis",
    name: "Paxis",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תפן",
    stage: "Seed",
    size: "1-10",
    founded: 2009,
    fundingM: 0,
    score: 71,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Paxis develops and manufactures specialty solutions for high end ballistic armor employing state of the art ceramic materials.",
  },
  {
    id: "eplane",
    name: "ePlane",
    country: "Israel",
    flag: "🇮🇱",
    hq: "בני ברק",
    stage: "Seed",
    size: "1-10",
    founded: 2017,
    fundingM: 0,
    score: 70,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "End-to-end Marketplace for the Aviation Industry",
  },
  {
    id: "sky-sapience",
    name: "Sky Sapience",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יוקנעם עילית",
    stage: "Seed",
    size: "1-10",
    founded: 2014,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Tethered Hovering Platforms",
  },
  {
    id: "combatica",
    name: "Combatica",
    country: "Israel",
    flag: "🇮🇱",
    hq: "פתח תקווה",
    stage: "Seed",
    size: "11-50",
    founded: 2021,
    fundingM: 0,
    score: 71,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Combatica develops a combat training XR simulator. The company's system uses sophisticated AI to activate the terrorists in simulation, both in battles and in investigations. It will allow squads to train in a realistic environment against AI-powered enemies or against each other.",
  },
  {
    id: "cpc",
    name: "CPC",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כרמיאל",
    stage: "Series A",
    size: "11-50",
    founded: 1984,
    fundingM: 0,
    score: 82,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "CPC offers end-to-end supply chain solutions of electro-mechanical products. The company's in-house manufacturing capabilities includes SMT assembly, digital printed electronics and tailor-made electro-mechanical assembly (B2S, B2P).",
  },
  {
    id: "wondernet",
    name: "WonderNet",
    country: "Israel",
    flag: "🇮🇱",
    hq: "אור יהודה",
    stage: "Seed",
    size: "11-50",
    founded: 1998,
    fundingM: 0,
    score: 79,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "WonderNet is an Innovative Software Factory founded in 1998, focusing on the development of the first commercial Biometric Signature Verification server. The verification server became the center of its authentic e-signature software systems, which enabled organizations to conduct trusted e-business transactions.",
  },
  {
    id: "aiphex",
    name: "AIPHEX",
    country: "Israel",
    flag: "🇮🇱",
    hq: "אור יהודה",
    stage: "Seed",
    size: "1-10",
    founded: 2024,
    fundingM: 0,
    score: 64,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "AIPHEX is an Israel-based defense company pioneering multi-physics AI platforms for sensing, autonomy, and navigation. Its systems, validated in operational combat with the Israel Defense Forces, deliver precision, resilience, and adaptability against next-generation threats.",
  },
  {
    id: "insignito",
    name: "Insignito",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "1-10",
    founded: 2023,
    fundingM: 0,
    score: 65,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Insignito empowers defense and security teams with novel stealth technology and explainable science to master signature analysis and drone design.",
  },
  {
    id: "plasan",
    name: "Plasan",
    country: "Israel",
    flag: "🇮🇱",
    hq: "קיבוץ שסא",
    stage: "Growth",
    size: "201-500",
    founded: 1985,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Plasan is a global leader in survivability and armor solutions, committed to protecting those who protect us across land, air, and sea. The company provides comprehensive survivability solutions, from armored vehicles designed and manufactured by Plasan to tailored protection and integrated systems for OEM platforms.",
  },
  {
    id: "edgybees",
    name: "EdgyBees",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הרצליה",
    stage: "Series A",
    size: "11-50",
    founded: 2016,
    fundingM: 0,
    score: 76,
    strategic: false,
    readiness: "",
    sectors: ["defense", "earth-obs"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Real-time Augmented Visual Intelligence",
  },
  {
    id: "flolive",
    name: "floLIVE",
    country: "Israel",
    flag: "🇮🇱",
    hq: "בני ברק",
    stage: "Series B",
    size: "51-200",
    founded: 2016,
    fundingM: 0,
    score: 82,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Cloud-based Connectivity Platform for IoT Devices",
  },
  {
    id: "comparts",
    name: "Comparts",
    country: "Israel",
    flag: "🇮🇱",
    hq: "פתח תקווה",
    stage: "Series A",
    size: "11-50",
    founded: 2005,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Comparts brings years of knowledge & expertise in the fields of aerodynamics, engineering, communications and production assembly for the design and production of composite materials.",
  },
  {
    id: "aeronautics",
    name: "Aeronautics",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יבנה",
    stage: "Series C",
    size: "201-500",
    founded: 1997,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Unmanned Aerial Systems and Defense Solutions",
  },
  {
    id: "ceva",
    name: "CEVA",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הרצליה",
    stage: "Series C",
    size: "201-500",
    founded: 2002,
    fundingM: 0,
    score: 93,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Signal-processing Platform and AI Processors",
  },
  {
    id: "lda",
    name: "LDA",
    country: "Israel",
    flag: "🇮🇱",
    hq: "",
    stage: "Seed",
    size: "1-10",
    founded: 2017,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "In stealth mode.",
  },
  {
    id: "defensoft",
    name: "DefenSoft",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יוקנעם עילית",
    stage: "Series A",
    size: "11-50",
    founded: 2002,
    fundingM: 0,
    score: 81,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "DEFENSOFT develops innovative software and methodologies to plan large-scale integrated border and perimeter security systems. The company's proprietary technology* utilizes non-trial-and-error automated calculations and planning procedures that enable customers to achieve optimal cost-effective designs.",
  },
  {
    id: "aurislink",
    name: "Aurislink",
    country: "Israel",
    flag: "🇮🇱",
    hq: "זיכרון יעקב",
    stage: "Seed",
    size: "1-10",
    founded: 2003,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Aurislink is a technology company specializing in acoustic sound detection and processing, with a particular focus on detecting gunshots and determining their location.",
  },
  {
    id: "d-fend",
    name: "D-Fend",
    country: "Israel",
    flag: "🇮🇱",
    hq: "רעננה",
    stage: "Series B",
    size: "51-200",
    founded: 2017,
    fundingM: 0,
    score: 85,
    strategic: false,
    readiness: "",
    sectors: ["defense", "sar"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "D-Fend is a developer of an autonomous counter-drone perimeter security system, designed to detect and identify intruding commercial drones automatically.",
  },
  {
    id: "rafael-advanced-defense-systems",
    name: "Rafael Advanced Defense Systems",
    country: "Israel",
    flag: "🇮🇱",
    hq: "באר שבע",
    stage: "Public",
    size: "1000+",
    founded: 1948,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data", "manufacturing", "sar"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Military Defense Systems and Related Commercial Applications",
  },
  {
    id: "intellicon",
    name: "Intellicon",
    country: "Israel",
    flag: "🇮🇱",
    hq: "זיכרון יעקב",
    stage: "Seed",
    size: "1-10",
    founded: 2011,
    fundingM: 0,
    score: 62,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Intelligent Traffic Signal Control",
  },
  {
    id: "innocon",
    name: "Innocon",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ראש העין",
    stage: "Seed",
    size: "1-10",
    founded: 2001,
    fundingM: 0,
    score: 65,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Unmanned Aerial Vehicles",
  },
  {
    id: "sightec",
    name: "Sightec",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Series A",
    size: "11-50",
    founded: 2010,
    fundingM: 0,
    score: 78,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Sightec is a Visual Situation Awareness system for autonomous flights that’s based on computer vision and artificial intelligence technologies.",
  },
  {
    id: "novalink",
    name: "NovaLink",
    country: "Israel",
    flag: "🇮🇱",
    hq: "מודיעין",
    stage: "Seed",
    size: "1-10",
    founded: 2025,
    fundingM: 0,
    score: 64,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "NovaLink is disrupting space communication. The company's optical satellite technology redefines what's possible in space communications.",
  },
  {
    id: "elta",
    name: "Elta",
    country: "Israel",
    flag: "🇮🇱",
    hq: "אשדוד",
    stage: "Public",
    size: "1000+",
    founded: 1967,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "ELTA Systems, a group and subsidiary of Israel Aerospace Industries, is one of Israel’s leading defense electronics companies and a global leader in the field of Intelligence, Surveillance, Target Acquisition and Reconnaissance (ISTAR), Early Warning and Control, Homeland Security (HLS), Self-Protec…",
  },
  {
    id: "powder-fuels",
    name: "Powder Fuels",
    country: "Israel",
    flag: "🇮🇱",
    hq: "יוקנעם עילית",
    stage: "Seed",
    size: "1-10",
    founded: 2019,
    fundingM: 0,
    score: 67,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Powder Fuels develops a rocket propulsion engine that uses an innovative energetic powder (a powder monopropellant) and related feeder-combustor hardware.",
  },
  {
    id: "always-connect-ai",
    name: "Always Connect AI",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כפר סבא",
    stage: "Seed",
    size: "1-10",
    founded: 2021,
    fundingM: 0,
    score: 68,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Always Connect AI is building the world’s first AI engine for satellite networks. The company's technology transforms traditional satellite systems into adaptive, self-learning networks that think, decide and optimize in real time.",
  },
  {
    id: "downwind",
    name: "DownWind",
    country: "Israel",
    flag: "🇮🇱",
    hq: "הוד השרון",
    stage: "Seed",
    size: "1-10",
    founded: 2018,
    fundingM: 0,
    score: 64,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Founded in 2008 by IDF ex-IAF pilots, DownWind is a well established brand in the unmanned air vehicles space.",
  },
  {
    id: "tat-technologies",
    name: "TAT Technologies",
    country: "Israel",
    flag: "🇮🇱",
    hq: "בני עיש",
    stage: "Series B",
    size: "51-200",
    founded: 1969,
    fundingM: 0,
    score: 86,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Aircraft Heat Exchangers, Valves, and Pumps",
  },
  {
    id: "elbit-systems",
    name: "Elbit Systems",
    country: "Israel",
    flag: "🇮🇱",
    hq: "חיפה",
    stage: "Public",
    size: "1000+",
    founded: 1966,
    fundingM: 0,
    score: 95,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Elbit Systems is an international high technology company engaged in a wide range of defense, homeland security and commercial programs throughout the world.",
  },
  {
    id: "perytons",
    name: "Perytons",
    country: "Israel",
    flag: "🇮🇱",
    hq: "נס ציונה",
    stage: "Seed",
    size: "1-10",
    founded: 2007,
    fundingM: 0,
    score: 64,
    strategic: false,
    readiness: "",
    sectors: ["defense", "comms", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "IoT Cybersecurity and Protocol Analysis Solutions",
  },
  {
    id: "aipex",
    name: "AIPEX",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ישראל",
    stage: "Seed",
    size: "1-10",
    founded: 2024,
    fundingM: 0,
    score: 56,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Anti-Missiles",
  },
  {
    id: "duram-mask",
    name: "Duram Mask",
    country: "Israel",
    flag: "🇮🇱",
    hq: "רמת הכובש",
    stage: "Seed",
    size: "1-10",
    founded: 1989,
    fundingM: 0,
    score: 71,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Emergency Personal Escape Masks",
  },
  {
    id: "cryptolon-technologies",
    name: "Cryptolon Technologies",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Seed",
    size: "1-10",
    founded: 2021,
    fundingM: 0,
    score: 61,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Advanced Network Encryption Solutions",
  },
  {
    id: "bes-electronic-systems",
    name: "BES Electronic Systems",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ראשון לציון",
    stage: "Seed",
    size: "1-10",
    founded: 1998,
    fundingM: 0,
    score: 65,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Military-grade Electronic Platforms",
  },
  {
    id: "parknav",
    name: "Parknav",
    country: "Israel",
    flag: "🇮🇱",
    hq: "תל אביב",
    stage: "Series A",
    size: "11-50",
    founded: 2021,
    fundingM: 0,
    score: 72,
    strategic: false,
    readiness: "",
    sectors: ["defense", "ai-data"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "On-Street Parking Solution",
  },
  {
    id: "aptos",
    name: "Aptos",
    country: "Israel",
    flag: "🇮🇱",
    hq: "ישראל",
    stage: "Seed",
    size: "1-10",
    founded: 2020,
    fundingM: 0,
    score: 58,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Space-Hardened Compute, Persistent Comms, and Cloud Services Integration",
  },
  {
    id: "euclid",
    name: "Euclid",
    country: "Israel",
    flag: "🇮🇱",
    hq: "בת חפר",
    stage: "Seed",
    size: "11-50",
    founded: 2006,
    fundingM: 0,
    score: 77,
    strategic: false,
    readiness: "",
    sectors: ["defense", "sar"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Smart Positioning Systems",
  },
  {
    id: "enertec-systems",
    name: "Enertec Systems",
    country: "Israel",
    flag: "🇮🇱",
    hq: "כרמיאל",
    stage: "Series A",
    size: "11-50",
    founded: 2001,
    fundingM: 0,
    score: 83,
    strategic: false,
    readiness: "",
    sectors: ["defense", "manufacturing"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Advanced Electronic Systems for Military and Civil Applications",
  },
  {
    id: "nando-drones",
    name: "Nando Drones",
    country: "Israel",
    flag: "🇮🇱",
    hq: "בני עטרות",
    stage: "Seed",
    size: "1-10",
    founded: 2017,
    fundingM: 0,
    score: 66,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Autonomous Drone-based Solutions",
  },
  {
    id: "blades-technology-limited",
    name: "Blades Technology Limited",
    country: "Israel",
    flag: "🇮🇱",
    hq: "נהריה",
    stage: "Seed",
    size: "1-10",
    founded: 1968,
    fundingM: 0,
    score: 71,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Turbine Blade and Vane Manufacturer",
  },
  {
    id: "aidymo-cv",
    name: "aidymo-cv",
    country: "Israel",
    flag: "🇮🇱",
    hq: "אשדוד",
    stage: "Seed",
    size: "1-10",
    founded: 2021,
    fundingM: 0,
    score: 61,
    strategic: false,
    readiness: "",
    sectors: ["defense", "earth-obs"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "Sensor-Fused Perception for Autonomous Systems",
  },
  {
    id: "rfisee",
    name: "RFISee",
    country: "Israel",
    flag: "🇮🇱",
    hq: "רעננה",
    stage: "Seed",
    size: "1-10",
    founded: 2016,
    fundingM: 0,
    score: 60,
    strategic: false,
    readiness: "",
    sectors: ["defense"],
    tech: [],
    offers: [],
    needs: [],
    customers: [],
    partners: [],
    overlap: [],
    blurb: "4D Imaging Radar",
  },
];

const PEOPLE = [
  {
    id: "maya",
    name: "מאיה לוי",
    role: "R&D AI Lead",
    dept: "R&D",
    avatar: "מ",
    color: "oklch(0.65 0.20 295)",
    interests: ["ai-data", "earth-obs", "sar"],
    focus: ["machine learning", "satellite imagery", "deep learning", "edge AI"],
    matches: ["elta", "bluebird-aero-systems", "edgybees", "omnisys", "strasa-technologies"],
  },
  {
    id: "avi",
    name: "אבי כהן",
    role: "Strategic Partnerships",
    dept: "Business Development",
    avatar: "א",
    color: "oklch(0.65 0.22 250)",
    interests: ["defense", "comms", "manufacturing"],
    focus: ["defense contracts", "B2G", "NATO", "export", "SATCOM"],
    matches: ["rafael-advanced-defense-systems", "elbit-systems", "israel-aerospace-industries", "plasan", "urban-aeronautics"],
  },
  {
    id: "roei",
    name: "רועי ברגמן",
    role: "Investment Director",
    dept: "Finance",
    avatar: "ר",
    color: "oklch(0.72 0.20 80)",
    interests: ["propulsion", "launchers", "energy"],
    focus: ["seed funding", "deep tech", "SpaceTech VC", "propulsion"],
    matches: ["wespace", "newrocket", "powder-fuels", "tehiru", "moonshot-space"],
  },
  {
    id: "neta",
    name: "נטע שרון",
    role: "Program Manager",
    dept: "Programs",
    avatar: "נ",
    color: "oklch(0.72 0.20 185)",
    interests: ["life-sci", "earth-obs", "ai-data"],
    focus: ["ESA programs", "scientific payloads", "dual-use", "space research"],
    matches: ["lulav-space", "creation-space", "moonscape", "exom"],
  },
  {
    id: "yoav",
    name: "יואב ספיר",
    role: "Technology Director",
    dept: "Technology",
    avatar: "י",
    color: "oklch(0.65 0.18 30)",
    interests: ["ai-data", "sar", "defense", "manufacturing"],
    focus: ["radar", "SAR", "RF systems", "signal intelligence"],
    matches: ["d-fend", "euclid", "microkim", "elta", "omnisys"],
  },
];

const CONNECTIONS = [
  { from: "elbit-systems", to: "israel-aerospace-industries", type: "Joint Program" },
  { from: "rafael-advanced-defense-systems", to: "israel-aerospace-industries", type: "Joint Program" },
  { from: "elta", to: "israel-aerospace-industries", type: "Joint Program" },
  { from: "plasan", to: "elbit-systems", type: "Supplier" },
  { from: "d-fend", to: "urban-aeronautics", type: "Technology Partnership" },
  { from: "lulav-space", to: "ramon-space", type: "Technology Partnership" },
  { from: "lulav-space", to: "spaceil", type: "Technology Partnership" },
  { from: "omnisys", to: "urban-aeronautics", type: "System Integration" },
  { from: "bluebird-aero-systems", to: "elbit-systems", type: "Supplier" },
  { from: "edgybees", to: "elbit-systems", type: "Technology Partnership" },
  { from: "wespace", to: "spaceil", type: "R&D Collaboration" },
  { from: "creation-space", to: "israel-aerospace-industries", type: "R&D Collaboration" },
  { from: "sightec", to: "d-fend", type: "Technology Partnership" },
  { from: "gorilla-link", to: "beeper", type: "Technology Partnership" },
];

const SECTOR_DIST = SECTORS.map((s) => ({
  ...s,
  count: COMPANIES.filter((c) => c.sectors.includes(s.id)).length,
})).filter((s) => s.count > 0).sort((a, b) => b.count - a.count);

const FUNNEL = [
  { stage: "נסרקו",   n: 580 },
  { stage: "פרופיל",  n: 110 },
  { stage: "הוערכו",  n: 68  },
  { stage: "Pilot",   n: 22  },
  { stage: "פעיל",    n: 10  },
];

const ACTIVITY = [
  { tag: "intro", who: "מאיה לוי",   what: "שלחה בקשת introduction ל-", to: "Elta Systems",    t: "לפני 12 דק׳" },
  { tag: "ai",    who: "AI",          what: "זיהה התאמה חדשה בין מאיה ל-", to: "D-Fend",        t: "לפני 28 דק׳" },
  { tag: "flag",  who: "אבי כהן",    what: "סימן כאסטרטגי:",              to: "Rafael",         t: "לפני 1 שע׳"  },
  { tag: "opp",   who: "רועי ברגמן", what: "פתח workspace עם",             to: "WeSpace",        t: "לפני 2 שע׳"  },
  { tag: "ai",    who: "AI",          what: "עדכן פרופיל:",                 to: "Lulav Space",    t: "לפני 3 שע׳"  },
  { tag: "intro", who: "נטע שרון",   what: "ביקשה meeting עם",             to: "Creation Space", t: "אתמול"       },
];

Object.assign(window, { SECTORS, STAGES, COMPANIES, PEOPLE, CONNECTIONS, SECTOR_DIST, FUNNEL, ACTIVITY });